### ISSUE TITLE
Linux support ?

### ISSUE THREAD

**Issue by chris-zen** [padenot/audio_thread_priority#1]
Hi, I am wondering if could it be possible to include support for Linux (if it actually makes sense). I am not an expert in the field but would like to contribute if you give me a clue on where to start looking at.

Best

**Comment by padenot** [comment]
This is not supported at the moment because it would require elevated privileges on Linux, and I've been writing this for Firefox, which is not running with elevated privileges.

Ideally we'd use `rtkit`, but it does not work on my machine (stock ubuntu 18.10), I'm missing some some caps probably. Even the program `rtkit-test` provided in `rtkit` does not work immediately. Maybe we should start by figuring out what is needed to have `rtkit` bump a thread to real-time prio.

**Comment by chris-zen** [comment]
@padenot thanks for the answer. After reading the `rtkit` [announcement thread](http://lalists.stanford.edu/lad/2009/06/0191.html) and this [article](https://lwn.net/Articles/339316/), I realised how complex the topic is for Linux. Now I understand that it is not just a matter of using a lib like [thread_priority](https://docs.rs/thread-priority/0.1.0/thread_priority/) to request a thread to be RT, but there are all kind of security measures that makes that a non trivial thing for the regular user (I am wondering why isn't this a problem for macOS or Win, perhaps they implement better scheduling policies for RT).

After some search for RealtimeKit, I was not able to find much information or documentation, so it is not really clear to me whether it is something dead or not, although it seems to be included in the repositories of several important distros.

I'll keep an eye for this in the background, and revisit this issue if I find new information.
Meanwhile, I'll keep using this lib for Win and macOS. Thank you very much for the contribution ;-)

**Comment by padenot** [comment]
I found a way to do this that works on my Ubuntu 18.10, without modification, and without root, as long as `rtkit` is installed, and it's a dep of PulseAudio, so it should be a reasonably common setup.

I'm going to update this crate when I have a minute, as it's going to be very important for us as well. I'll write something up.

Thanks for opening this issue that prompted me to have another look at this, and thanks to @jcristau here in the office that found why the `rtkit` examples weren't working (a nanosecond vs. microsecond unit mismatch) and fixed them. This was in patch already [patched in debian](https://sources.debian.org/src/rtkit/0.11-6/debian/patches/0003-Fix-rtkit-test.patch/), as he pointed out later.

**Comment by padenot** [comment]
#2 does most of what's needed here, thanks @jcristau.

I'll update later to something that makes sense based on the buffer size and the sample-rate, so that we request what the audio callback needs, not more, but this will work for now. I'll also check that the scheduler is truly back to normal when demoting the thread.

**Comment by chris-zen** [comment]
@padenot great news ! Thanks a lot !
Looking forward for the release to crates.io ;-)

**Comment by padenot** [comment]
>  Looking forward for the release to crates.io ;-)

It's been released for some time now, fwiw.
